version: '3'
vars:
  env_file: .env.linux

tasks:
  migrate:
    desc: "Run Prisma migrations"
    cmds:
      - docker-compose --env-file {{.env_file}} -f /home/wsl/work/java/demo/docker/db/docker-compose.yaml run --rm app npm run prisma:migrate

  studio:
    desc: "Run Prisma Studio"
    cmds:
      - docker-compose -f /home/wsl/work/java/demo/docker/db/docker-compose.yaml exec app npm run prisma:studio

  up:
    desc: "Start containers"
    cmds:
      - docker-compose -f /home/wsl/work/java/demo/docker/db/docker-compose.yaml up -d

  down:
    desc: "Stop containers"
    cmds:
      - docker-compose -f /home/wsl/work/java/demo/docker/db/docker-compose.yaml down

  build:
    desc: "Build and start containers"
    cmds:
      - docker-compose -f /home/wsl/work/java/demo/docker/db/docker-compose.yaml up --build -d
