services:
  postgres:
    container_name: java_demo_postgres
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - my-bridge-network

volumes:
  pg_data:

networks:
  my-bridge-network:
    driver: bridge
