version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_prisma_db
    volumes:
      - ./prisma:/app/prisma # Mount thư mục prisma
      - ./package.json:/app/package.json # Mount thư mục prisma
    environment:
      DATABASE_URL: ${DATABASE_URL} # Không cần dấu ':' ở đây
    command: npx prisma migrate dev # Sửa lại lệnh chạy migration cho Prisma
    networks:
      - my-bridge-network

networks:
  my-bridge-network:
    driver: bridge